import { expect, test } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test('MVP-10/13: manual fixture, validated squad and availability forms', async ({ page }) => {
  const writes: string[] = [];
  page.on('request', (request) => { if (request.method() !== 'GET') writes.push(request.url()); });
  await page.goto('/dev/admin');
  await expect(page.getByRole('heading', { name: 'The club desk.' })).toBeVisible();
  await page.getByLabel('Opponent', { exact: true }).fill('Synthetic Admin FC');
  await page.getByLabel('Kickoff with timezone').fill('2026-10-25T12:00:00');
  await page.getByRole('button', { name: 'Create fixture', exact: true }).click();
  await expect(page.locator('.admin-error')).toBeVisible();
  await expect(page.getByLabel('Opponent', { exact: true })).toHaveValue('Synthetic Admin FC');
  await page.getByLabel('Kickoff with timezone').fill('');
  await page.getByRole('button', { name: 'Create fixture', exact: true }).click();
  await expect(page.getByText('Applied in this preview only.', { exact: false })).toBeVisible();
  await page.getByLabel('Featured match').selectOption({ label: 'Synthetic Admin FC · scheduled' });
  await expect(page.getByText('Manual featured selection is active.')).toBeVisible();
  await page.getByRole('button', { name: 'Squad', exact: true }).click();
  await page.getByLabel('Edit player').selectOption({ label: '1 · Senne Lammens' });
  await page.getByLabel('Shirt number', { exact: true }).fill('2');
  await page.getByRole('button', { name: 'Save player', exact: true }).click();
  await expect(page.locator('.admin-error')).toContainText('unique');
  await page.getByLabel('Active', { exact: true }).uncheck();
  await page.getByLabel('Shirt number', { exact: true }).fill('');
  await page.getByRole('button', { name: 'Save player', exact: true }).click();
  await expect(page.getByLabel('Active', { exact: true })).not.toBeChecked();
  await page.getByRole('button', { name: 'Availability', exact: true }).click();
  await page.getByLabel('Availability: Senne Lammens', { exact: true }).selectOption('unavailable');
  await expect(page.getByLabel('Availability: Senne Lammens', { exact: true })).toHaveValue('unavailable');
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()).violations).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(writes).toEqual([]);
  await page.screenshot({ path: `test-results/admin-${test.info().project.name}.png`, fullPage: true });
  await page.reload();
  await expect(page.getByLabel('Featured match').locator('option')).toHaveCount(1);
});
