import { expect, test } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test('MVP-10/13: manual fixture, validated squad and availability forms', async ({ page }) => {
  const writes: string[] = [];
  page.on('request', (request) => { if (request.method() !== 'GET') writes.push(request.url()); });
  await page.goto('/dev/admin');
  await expect(page.getByRole('heading', { name: 'The club desk.' })).toBeVisible();
  await page.getByLabel('Opponent', { exact: true }).fill('Synthetic Admin FC');
  await page.getByLabel('Kickoff with timezone').fill('2026-10-25T12:00:00');
  await page.getByRole('button', { name: 'Create fixture', exact: true }).click();
  await expect(page.locator('.admin-error')).toBeVisible();
  await expect(page.getByLabel('Opponent', { exact: true })).toHaveValue('Synthetic Admin FC');
  await page.getByLabel('Kickoff with timezone').fill('');
  await page.getByRole('button', { name: 'Create fixture', exact: true }).click();
  await expect(page.getByText('Applied in this preview only.', { exact: false })).toBeVisible();
  await page.getByLabel('Featured match').click();
  await page.getByRole('option', { name: 'Synthetic Admin FC · scheduled', exact: true }).click();
  await expect(page.getByText('Manual featured selection is active.')).toBeVisible();
  await page.getByRole('tab', { name: 'Squad', exact: true }).click();
  await page.getByLabel('Edit player').fill('Lammens');
  await page.getByRole('option', { name: '1 · Senne Lammens', exact: true }).click();
  await page.getByLabel('Shirt number', { exact: true }).fill('2');
  await page.getByRole('button', { name: 'Save player', exact: true }).click();
  await expect(page.locator('.admin-error')).toContainText('unique');
  await page.getByLabel('Active', { exact: true }).uncheck();
  await page.getByLabel('Shirt number', { exact: true }).fill('');
  await page.getByRole('button', { name: 'Save player', exact: true }).click();
  await expect(page.getByLabel('Active', { exact: true })).not.toBeChecked();
  await page.getByRole('tab', { name: 'Availability', exact: true }).click();
  const ongoing = page.getByRole('combobox', { name: 'Ongoing availability: Senne Lammens', exact: true });
  const match = page.getByRole('combobox', { name: 'Availability: Senne Lammens', exact: true });
  await ongoing.click();
  await page.getByRole('option', { name: 'Unavailable until cleared', exact: true }).click();
  await expect(match.locator('..')).toContainText('Use default (Unavailable)');
  await match.click();
  await page.getByRole('option', { name: 'Available', exact: true }).click();
  await expect(match.locator('..')).toContainText('Available');
  await expect(ongoing.locator('..')).toContainText('Unavailable until cleared');
  await match.click();
  await page.getByRole('option', { name: 'Use default (Unavailable)', exact: true }).click();
  await expect(match.locator('..')).toContainText('Use default (Unavailable)');
  await ongoing.click();
  await page.getByRole('option', { name: 'Available by default', exact: true }).click();
  await expect(match.locator('..')).toContainText('Use default (Available)');
  await page.getByRole('combobox', { name: 'Availability: Senne Lammens', exact: true }).click();
  await page.getByRole('option', { name: 'Unavailable', exact: true }).click();
  await expect(page.getByRole('combobox', { name: 'Availability: Senne Lammens', exact: true }).locator('..')).toContainText('Unavailable');
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()).violations).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(writes).toEqual([]);
  await page.screenshot({ path: `test-results/admin-${test.info().project.name}.png`, fullPage: true });
  await page.reload();
  await page.getByLabel('Featured match').click();
  await expect(page.getByRole('option')).toHaveCount(1);
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()).violations).toEqual([]);
});

test('MVP-10/13: fixture editing with keyboard and accessible Ant Design sections', async ({ page }) => {
  await page.goto('/dev/admin');
  await expect(page.getByText('Lineups lock 15 minutes after kickoff.', { exact: false })).toBeVisible();
  await page.getByLabel('Opponent', { exact: true }).fill('Synthetic Keyboard FC');
  await page.getByLabel('Kickoff with timezone').fill('2026-10-25T16:30:00+00:00');
  await page.getByRole('button', { name: 'Create fixture', exact: true }).focus();
  await page.keyboard.press('Enter');
  await expect(page.getByRole('status')).toContainText('Applied in this preview only.');
  await page.getByLabel('Edit fixture').focus();
  await page.keyboard.press('ArrowDown');
  await page.keyboard.press('ArrowDown');
  await page.keyboard.press('Enter');
  await expect(page.getByLabel('Opponent', { exact: true })).toHaveValue('Synthetic Keyboard FC');
  await page.getByLabel('Opponent', { exact: true }).fill('Synthetic Revised FC');
  await page.getByRole('button', { name: 'Save fixture', exact: true }).click();
  await expect(page.getByLabel('Opponent', { exact: true })).toHaveValue('Synthetic Revised FC');
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()).violations).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: `test-results/admin-fixtures-${test.info().project.name}.png`, fullPage: true });
});
